version: '3.3'

services:
  mysqldb:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=edwiges
    volumes:
    - mysqlVolume:/var/lib/mysql
    - mysqlConfig:/etc/mysql

  docker-python:
    build:
      context: .
    ports:
    - 3000:5000
    depends_on:
      - mysqldb

volumes:
  mysqlVolume:
  mysqlConfig:
